<?php

namespace Dakalab\DivisionCode;

use Symfony\Component\DomCrawler\Crawler;

/**
 * Upgrader class is used to update the codes array file.
 *
 * The source data is from official website of "Ministry of Civil Affairs of PRC"
 */
class Upgrader extends DivisionCode
{
    protected function getListURL(): string
    {
        return 'http://www.mca.gov.cn/article/sj/xzqh/' . date('Y');
    }

    protected function getLatestCodesURL(): string
    {
        $html = file_get_contents($this->getListURL());

        $crawler = new Crawler($html);

        $crawler = $crawler->filter('a:contains("县以上行政区划代码")');

        return 'http://www.mca.gov.cn' . $crawler->getNode(0)->getAttribute('href');
    }

    public function getCodes(): array
    {
        $html = file_get_contents($this->getLatestCodesURL());

        // need to redirect
        if (preg_match('/http:\/\/www\.mca\.gov\.cn\/article\/sj\/xzqh\/.+\.html/U', $html, $m)) {
            $html = file_get_contents($m[0]);
        }

        $crawler = new Crawler($html);

        $crawler = $crawler->filterXPath('//tr[@height=19]');

        $codes = [];
        foreach ($crawler as $tr) {
            $td = (new Crawler($tr))->filter('td');
            $codes[$td->getNode(1)->nodeValue] = $td->getNode(2)->nodeValue;
        }

        return $codes;
    }

    public function upgrade()
    {
        $codes = $this->getCodes();
        $content = "<?php\n// Codes generated by Upgrader. DO NOT EDIT.\n";
        $content .= 'return ';
        $content .= var_export($codes, true);
        $content .= ";\n";

        return file_put_contents($this->getCodesFile(), $content);
    }
}
